before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: sTALubq4j861m/j6a8YSz8jkYL6EPwztG3FphqciM3x853knyfhTih2LPW9eLhwcxGQ0M4eQBtcOg69XYo8QbJb3GEzr6fzYvVJsfiOMxd3LDyn36nQ5Z10A/xHFrhH8Op0H2T2d8btrjDK4AyrLq9RUqAnXbtpy0HVgA+7eVkfzkgkw2maeBdnwJGB2f4yhO8RCFCLyFgQGOgU1g3DILtmEGcCCQtv1KS1vVSZUT7oxN4QI5Gczm/6yzca5qUqCylG9SI8fP8UpBkyn7CCOSeNxewM4504IoDvPpvT7BjYbqZRRhpeeOW06s6gmt5c5Fm7rg2t3wIrBUPu3WkzViF7hZZgSDMWk/u8fUGbPUDw5C6ww0gC3ctpYJrbFf0lFq9XqkT3ZnxeD5g/XOqh28id1sUI+V+wQg8ekkKRfkKSfdSLfeKdcRk/Cl+m/nesxtjNB/WSC38b6zxsRKIu7k/JmzPI/at2DepjN+vC+TLuSP6HODKJT5axlJywHYspA4qWeN0hNchmWqlSgUqLnbtOd6bJRWfQWcPWHmYNqB+bD35BXNvClKPLGhsnqN6BGNNHG4RkEqqFJYZ+XdjtXikY9JJ7BoDv83USdIM/JljCOWNyiWr8ZrWD26ddQvshJ7ikz4Mpr3rQSJK4G2j8nK23cT28k1l0kaFm+TyAIP40= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
